\" Manpage for pdftools.
.\" Contact leonhad@gmail.com to support.
.TH man 1 "05 Jan 2012" "0.1" "pdftools man page"
.SH NAME
pdftools \- convert PDF files to azw or epub formats.
.SH SYNOPSIS
pdftools <inputfilename> <outputfilename>
.SH DESCRIPTION
pdftools is high level tools to convert PDF files to AZW or EPUB formats.
.SH OPTIONS
The pdftools take two mandatory inputs. <inputfilename> the name of PDF filename. <outputfilename> the name of new file converted.
.SH BUGS
No known bugs.
.SH AUTHOR
Leonardo Alves <leonhad@gmail.com>
